FaleMais/Models/Plane.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FaleMais.Models
{
    public class Plane
    {
        public int Id { get; set; }

        [Display(Name = "DDD Origem")]
        public string Origin { get; set; }

        [Display(Name = "DDD Destino")]
        public string Destiny { get; set; }

        [Display(Name = "Preço por min")]
        [DisplayFormat(DataFormatString = "R$ {0:F2}")]
        public double PricePerMinute { get; set; }

        [Display(Name = "Tempo da Ligação")]
        [DataType(DataType.Time)]
        public TimeSpan Time { get; set; }

        [Display(Name = "Plano FaleMais")]
        [DisplayFormat(DataFormatString = "FaleMais {0}")]
        public int SpeakMorePlane { get; set; }

        [Display(Name = "Sem FaleMais")]
        [DisplayFormat(DataFormatString = "R$ {0:F2}")]
        public double CallValue { get; set; }

        [Display(Name = "Com FaleMais")]
        [DisplayFormat(DataFormatString = "R$ {0:F2}")]
        public double PlaneCallValue { get; set; }
        
        public Plane()
        {
        }

        public Plane(int id, string origin, string destiny, double pricePerMinute)
        {
            Id = id;
            Origin = origin;
            Destiny = destiny;
            PricePerMinute = pricePerMinute;
        }

        public Plane(int id, string origin, string destiny, double pricePerMinute, TimeSpan time, int speakMorePlane, double callValue, double planeCallValue) : this(id, origin, destiny, pricePerMinute)
        {
            Time = time;
            SpeakMorePlane = speakMorePlane;
            CallValue = callValue;
            PlaneCallValue = planeCallValue;
        }
    }
}

FaleMais/Models/ViewModel/ErrorViewModel.cs
using System;

namespace FaleMais.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FaleMais/Models/ViewModel/PlaneFormViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FaleMais.Services;

namespace FaleMais.Models.ViewModel
{
    public class PlaneFormViewModels
    {
        public Plane Plane { get; set; }
        public IEnumerable<String> Origens { get; set; }
        public IEnumerable<String> Destinys { get; set; }
        public ICollection<int> Planes { get; set; }
    }
}

FaleMais/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FaleMais.Models;

namespace FaleMais.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Somos uma empresa especializada em chamadas de longa distância nacional, temos preocupação em trazer transparência de nossos serviços junto a nossos clientes.";

            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FaleMais/Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FaleMais.Services;
using FaleMais.Models.ViewModel;
using FaleMais.Models;

namespace FaleMais.Controllers
{
    public class PlanesController : Controller
    {
        private readonly PlaneService _planeService;

        public PlanesController(PlaneService planeService)
        {
            _planeService = planeService;
        }
        
        public IActionResult Index()
        {
            var list = _planeService.FindAll();
            return View(list);
        }

        public IActionResult Simulation()
        {
            var planes = _planeService.FindAll();
            var origens = planes.Select(plane => plane.Origin);
            var destinos = planes.Select(plane => plane.Destiny);
            var newPlanes = new List<int>();
            newPlanes.Add(30);
            newPlanes.Add(60);
            newPlanes.Add(120);
            var viewModel = new PlaneFormViewModels { Origens = origens, Destinys = destinos, Planes = newPlanes };
            return View(viewModel);
        }


        public IActionResult Simulator(PlaneFormViewModels obj)
        {

            var newPlane = _planeService.SetNewPlane(_planeService.GetPlane(obj.Plane));

            if (newPlane == null)
            {
                return NotFound();
            }
            return View(newPlane);
        }

        public IActionResult Planes()
        {
            return View();
        }
    }
}

FaleMais/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Quem Somos";
}
<h2>@ViewData["Title"]</h2>
<br />
<p>@ViewData["Message"]</p>

FaleMais/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contato";
}
<h2>@ViewData["Title"]</h2>
<br />


<address>
    São Paulo - SP<br />
    Redmond, WA 98052-6399<br />
    Telefone: (11) 5.5522.1264
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@telzir.com.br">Support@telzir.com.br</a><br />
    <strong>Dúvidas:</strong> <a href="mailto:Duvidas@telzir.com.br">Duvidas@telzir.com.br</a>
</address>

FaleMais/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/main2.jpeg" alt="ASP.NET" class="img-responsive img-rounded" />
            <div class="carousel-caption" role="option">
                <p>
                    Serviço especializado para lhe atender melhor.
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/main3.jpeg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Infraestrutura preparada.
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-6">
        <h3>Fale Conosco</h3>
        <ul>
            <li>E-mail:<a href="mailto:telzircontato@telzir.com.br"> telzircontato@telzir.com.br</a></li>
            <li>Telefone: (11) 5.5522.1264</li>
            <li>Skype: telzirskype@telzir.com.br</li>
        </ul>
    </div>
</div>

FaleMais/Views/Planes/Index.cshtml
@model IEnumerable<FaleMais.Models.Plane>

@{
    ViewData["Title"] = "Serviços";
}

<h2>@ViewData["Title"]</h2>

<hr />
<h4>Preços por ligação</h4>
<table class="table table-striped table-hover">
    <thead>
        <tr class="success">
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destiny)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PricePerMinute)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Origin)
            </td>
            <td>
                 @Html.DisplayFor(modelItem => item.Destiny)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PricePerMinute)
            </td>
        </tr>
        }
    </tbody>
</table>
Faça a Simulação de uma ligação com um de nossos planos <a asp-action="Simulation">Aqui</a>

FaleMais/Views/Planes/Planes.cshtml
@{
    ViewData["Title"] = "Planos";
}

<h2>@ViewData["Title"]</h2>
<br />
<h4>Disponiveis</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <table class="table table-condensed">
            <thead>
                <tr class="success">
                    <th>FaleMais</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>30 Minutos</td>
                </tr>
                <tr>
                    <td>60 Minutos</td>
                </tr>
                <tr>
                    <td>120 Minutos</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<a asp-action="Simulation" class="btn btn-default">Faça uma Simulação</a>

FaleMais/Views/Planes/Simulation.cshtml
@model FaleMais.Models.ViewModel.PlaneFormViewModels

@{
    ViewData["Title"] = "Simulação de Plano";
}

<br />
<h2>@ViewData["Title"]</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <h4>Selecione</h4>
        <form asp-action="Simulator">
            <div></div>
            <div class="form-group">
                <label class="control-label" asp-for="@Model.Plane.Origin"></label>
                <select asp-for="@Model.Plane.Origin" asp-items="@new SelectList(Model.Origens)" class="form-control"></select>
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="@Model.Plane.Destiny"></label>
                <select asp-for="@Model.Plane.Destiny" asp-items="@new SelectList(Model.Destinys)" class="form-control"></select>
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="@Model.Plane.Time"></label>
                <input class="form-control" asp-for="@Model.Plane.Time" />
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="@Model.Plane.SpeakMorePlane"></label>
                <select asp-for="@Model.Plane.SpeakMorePlane" asp-items="@new SelectList(Model.Planes)" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Simular" />
            </div>
        </form>
        <a asp-action="Index">Voltar</a>
    </div>
</div>

FaleMais/Views/Planes/Simulator.cshtml
@model FaleMais.Models.Plane

@{
    ViewData["Title"] = "Simulação";
}

<br />
<h2>@ViewData["Title"]</h2>
<hr />


<table class="table table-striped table-hover">
    <thead>
        <tr class="success">
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destiny)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpeakMorePlane)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaneCallValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CallValue)
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Origin)
            </td>
            <td>
                @Html.DisplayFor(model => model.Destiny)
            </td>
            <td>
                @Html.DisplayFor(model => model.Time)
            </td>
            <td>
                @Html.DisplayFor(model => model.SpeakMorePlane)
            </td>
            <td>
                @Html.DisplayFor(model => model.PlaneCallValue)
            </td>
            <td>
                @Html.DisplayFor(model => model.CallValue)
            </td>
        </tr>
    </tbody>
</table>
<a asp-action="Simulation">Voltar</a>

FaleMais/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Telzir</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-custom.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Telzir</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Planes" asp-action="Index">Serviços</a></li>
                    <li><a asp-area="" asp-controller="Planes" asp-action="Planes">Planos</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Quem Somos</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contato</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Telzir</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>